name: more
version: 3.6.0

homepage: https://github.com/renggli/dart-more
description: More Dart — Literally. Collecting, iterating, caching, mathematics,
  matching, ordering, and formatting easily.

environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  characters: ^1.2.0
  clock: ^1.1.0
  collection: ^1.15.0
  meta: ^1.7.0
dev_dependencies:
  args: ^2.3.0
  fake_async: ^1.2.0
  lints: ^1.0.0
  test: ^1.20.0
