name: more
version: 3.0.1

homepage: https://github.com/renggli/dart-more
description: More Dart — Literally. Collecting, iterating, caching, mathematics,
  matching, ordering, and formatting easily.

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  characters: ^1.1.0
  clock: ^1.1.0
  collection: ^1.15.0
  meta: ^1.3.0
dev_dependencies:
  fake_async: ^1.2.0
  test: ^1.16.0
