name: more
version: 3.10.0

homepage: https://github.com/renggli/dart-more
description: More Dart — Literally. Collecting, iterating, caching, mathematics,
  matching, ordering, and formatting easily.

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  characters: ^1.3.0
  clock: ^1.1.0
  collection: ^1.17.0
  meta: ^1.9.0
dev_dependencies:
  args: ^2.4.0
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.0
  fake_async: ^1.3.0
  lints: ^2.0.0
  test: ^1.23.0